### ISSUE TITLE
[BUG] Getting an error when running

### ISSUE THREAD

**Issue by S1mp1yDucky** [TecEash1/Taurus#27]
### 🚀 Are you trying to Self Host the bot?

- [X] I am using the official bot

### 🤔 Current Behavior

Error: The specified module could not be found.

### ✅ Expected Behavior

Run normally

### 📝 Steps To Reproduce

use start.bat

### ℹ️ Anything else?

![image](https://github.com/TecEash1/Taurus/assets/33154919/4e801bb3-3f7e-448e-a72b-65582471a7a6)

**Comment by TecEash1** [comment]
Hi! This is a known issue and is a bug in the tensorflow library to fix it please do the following:

move 
``D:\TFJS\node_modules\@tensorflow\tfjs-node\deps\lib\tensorflow.dll`` to`` D:\TFJS\node_modules\@tensorflow\tfjs-node\lib\napi-v8\``

On some devices, it works fine, whilst on others it doesn't.

**Comment by S1mp1yDucky** [comment]
checking...

**Comment by S1mp1yDucky** [comment]
![image](https://github.com/TecEash1/Taurus/assets/33154919/44e96d4f-f10d-4a40-92d9-b31314d35604)

New error

**Comment by TecEash1** [comment]
Thats weird, I have never seen that before... did you fill out your ``config.json`` file correctly?

**Comment by S1mp1yDucky** [comment]
Yes i did

**Comment by S1mp1yDucky** [comment]
fixed by removing uppercase letter
![image](https://github.com/TecEash1/Taurus/assets/33154919/21023d6f-9549-482b-b796-0537b70988be)

**Comment by TecEash1** [comment]
Sorry! Didnt realise you added/edited commands, but yea Discord doesn't support capital letters or spaces in names. Glad everything is working now!
