### ISSUE TITLE
[BUG] Adding custom commands

### ISSUE THREAD

**Issue by S1mp1yDucky** [TecEash1/Taurus#32]
### 🚀 Are you trying to Self Host the bot?

- [X] I am using the official bot

### 🤔 Current Behavior

I added my own commands to the bot to make the /image command premium users only included /addpremium, /removepremium, /gencode, /redeem. But whenever i run them it throws an error

### ✅ Expected Behavior

Run as normal

### 📝 Steps To Reproduce

start.bat

### ℹ️ Anything else?

![image](https://github.com/TecEash1/Taurus/assets/33154919/5c72aa90-8c45-4c56-a933-64f63badbc39)

**Comment by TecEash1** [comment]
that’s an issue on your side and with your commands. I would suggest debugging the issues with logging statements. *Not sure how I can help with that issue otherwise…*

**Comment by S1mp1yDucky** [comment]
This is what i did, it should work normally

```js
const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fs = require("fs");

module.exports = {
    data: new SlashCommandBuilder()
        .setName("addpremium")
        .setDescription("Give premium to a user.")
        .addUserOption((option) =>
            option.setName("user").setDescription("The user to give premium.").setRequired(true),
        ),

    async execute(interaction) {
        if (interaction.user.id !== 'OWNER_ID') {
            const ownerOnlyEmbed = new EmbedBuilder()
                .setDescription(":x: This command is for the bot owner only.")
                .setColor("#FF0000"); // Red color for errors
            return interaction.reply({ embeds: [ownerOnlyEmbed] });
        }
        const userId = interaction.options.getUser("user").id;
        const premiumUsers = JSON.parse(fs.readFileSync("premium_users.json"));

        if (premiumUsers.includes(userId)) {
            const alreadyPremiumEmbed = new EmbedBuilder()
                .setDescription(`<@${userId}> is already a premium user.`)
                .setColor("#FF0000"); // Red color for errors
            return interaction.reply({ embeds: [alreadyPremiumEmbed] });
        }

        premiumUsers.push(userId);
        fs.writeFileSync("premium_users.json", JSON.stringify(premiumUsers));

        const successEmbed = new EmbedBuilder()
            .setDescription(`:white_check_mark: Premium status has been added to <@${userId}> successfully.`)
            .setColor("#00FF00"); // Green color for success
        await interaction.reply({ embeds: [successEmbed] });
    },
};
```

**Comment by S1mp1yDucky** [comment]
Whatever command i make just does not work.

**Comment by TecEash1** [comment]
I am not sure, at some point, your code is not working. You can debug this with the logging statements. Custom commands do work, you can test this by creating a new command in the slash commands directory and then make it so that the bot sends a simple message when it’s executed.

**Comment by S1mp1yDucky** [comment]
okay trying

**Comment by S1mp1yDucky** [comment]
that works

**Comment by S1mp1yDucky** [comment]
what about the code above? why is it not working

**Comment by S1mp1yDucky** [comment]
i made it work. im stupid

**Comment by TecEash1** [comment]
glad you managed to fix the issue!
