### ISSUE TITLE
[BUG] getting error when using /taurusai command

### ISSUE THREAD

**Issue by S1mp1yDucky** [TecEash1/Taurus#37]
### 🚀 Are you trying to Self Host the bot?

- [X] I am using the official bot

### 🤔 Current Behavior

GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent: [400 Bad Request] Invalid value at 'system_instruction' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), "You are Sarah!
 Please greet the user with a greeting and then their name which is: <@986498137168441364> and limit your responses to 2000 characters or less. The user's status/presence is currently:
mobile: online" [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"system_instruction","description":"Invalid value at 'system_instruction' (type.googleapis.com/google.ai.generativelanguage.v1beta.Content), \"You are Sarah!\n Please greet the user with a greeting and then their name which is: <@986498137168441364> and limit your responses to 2000 characters or less. The user's status/presence is currently:\nmobile: online\""}]}]

### ✅ Expected Behavior

work normally

### 📝 Steps To Reproduce

bot.js

### ℹ️ Anything else?

![image](https://github.com/TecEash1/Taurus/assets/33154919/faa10757-9883-457c-8650-e6cfa1c693fb)

**Comment by TecEash1** [comment]
Hi could you please run ``pnpm i``. It is likely that your packages are on a previous version, and you have updated your bot without updating the packages. 

- For future reference if you update/restart the bot via the CLI it checks for any package changes automatically and updates the bot. 
- Also if an update includes ``📦 Updates Packages`` I would highly suggest running ``pnpm i`` after updating to stop any potential issues from occurring (If you update via the CLI this is not needed)

**Comment by S1mp1yDucky** [comment]
resolved! thank you
